
class Constant:
    CARD_CLICKED = 1  
    CARD_NOT_CLICKED = 2  
    NUT_SELECTED = 3  
    PEASHOOTER_SELECTED = 4 
    SUNFLOWER_SELECTED = 5
    SNOWPEA_SELECTED = 6 
    SPIKEWEED_SELECTED = 7  
    SHOVEL_SELECTED = 8
